/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WispyRouteImport } from './routes/wispy'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as SupportRouteImport } from './routes/support'
import { Route as RankingsbackupRouteImport } from './routes/rankings backup'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectIdRouteImport } from './routes/subject.$id'
import { Route as ProfileEditRouteImport } from './routes/profile_.edit'
import { Route as PracticeIdRouteImport } from './routes/practice.$id'
import { Route as ChapterIdRouteImport } from './routes/chapter.$id'
import { Route as LessonChapterIdLessonIdRouteImport } from './routes/lesson.$chapterId.$lessonId'

const WispyRoute = WispyRouteImport.update({
  id: '/wispy',
  path: '/wispy',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsbackupRoute = RankingsbackupRouteImport.update({
  id: '/rankings backup',
  path: '/rankings backup',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectIdRoute = SubjectIdRouteImport.update({
  id: '/subject/$id',
  path: '/subject/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile_/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIdRoute = PracticeIdRouteImport.update({
  id: '/practice/$id',
  path: '/practice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChapterIdRoute = ChapterIdRouteImport.update({
  id: '/chapter/$id',
  path: '/chapter/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonChapterIdLessonIdRoute = LessonChapterIdLessonIdRouteImport.update({
  id: '/lesson/$chapterId/$lessonId',
  path: '/lesson/$chapterId/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/learn': typeof LearnRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/rankings backup': typeof RankingsbackupRoute
  '/support': typeof SupportRoute
  '/tests': typeof TestsRoute
  '/wispy': typeof WispyRoute
  '/chapter/$id': typeof ChapterIdRoute
  '/practice/$id': typeof PracticeIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/subject/$id': typeof SubjectIdRoute
  '/lesson/$chapterId/$lessonId': typeof LessonChapterIdLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/learn': typeof LearnRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/rankings backup': typeof RankingsbackupRoute
  '/support': typeof SupportRoute
  '/tests': typeof TestsRoute
  '/wispy': typeof WispyRoute
  '/chapter/$id': typeof ChapterIdRoute
  '/practice/$id': typeof PracticeIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/subject/$id': typeof SubjectIdRoute
  '/lesson/$chapterId/$lessonId': typeof LessonChapterIdLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/learn': typeof LearnRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/rankings backup': typeof RankingsbackupRoute
  '/support': typeof SupportRoute
  '/tests': typeof TestsRoute
  '/wispy': typeof WispyRoute
  '/chapter/$id': typeof ChapterIdRoute
  '/practice/$id': typeof PracticeIdRoute
  '/profile_/edit': typeof ProfileEditRoute
  '/subject/$id': typeof SubjectIdRoute
  '/lesson/$chapterId/$lessonId': typeof LessonChapterIdLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/history'
    | '/home'
    | '/learn'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/rankings'
    | '/rankings backup'
    | '/support'
    | '/tests'
    | '/wispy'
    | '/chapter/$id'
    | '/practice/$id'
    | '/profile/edit'
    | '/subject/$id'
    | '/lesson/$chapterId/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/history'
    | '/home'
    | '/learn'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/rankings'
    | '/rankings backup'
    | '/support'
    | '/tests'
    | '/wispy'
    | '/chapter/$id'
    | '/practice/$id'
    | '/profile/edit'
    | '/subject/$id'
    | '/lesson/$chapterId/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/history'
    | '/home'
    | '/learn'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/rankings'
    | '/rankings backup'
    | '/support'
    | '/tests'
    | '/wispy'
    | '/chapter/$id'
    | '/practice/$id'
    | '/profile_/edit'
    | '/subject/$id'
    | '/lesson/$chapterId/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  LearnRoute: typeof LearnRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  RankingsRoute: typeof RankingsRoute
  RankingsbackupRoute: typeof RankingsbackupRoute
  SupportRoute: typeof SupportRoute
  TestsRoute: typeof TestsRoute
  WispyRoute: typeof WispyRoute
  ChapterIdRoute: typeof ChapterIdRoute
  PracticeIdRoute: typeof PracticeIdRoute
  ProfileEditRoute: typeof ProfileEditRoute
  SubjectIdRoute: typeof SubjectIdRoute
  LessonChapterIdLessonIdRoute: typeof LessonChapterIdLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wispy': {
      id: '/wispy'
      path: '/wispy'
      fullPath: '/wispy'
      preLoaderRoute: typeof WispyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings backup': {
      id: '/rankings backup'
      path: '/rankings backup'
      fullPath: '/rankings backup'
      preLoaderRoute: typeof RankingsbackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$id': {
      id: '/subject/$id'
      path: '/subject/$id'
      fullPath: '/subject/$id'
      preLoaderRoute: typeof SubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/edit': {
      id: '/profile_/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$id': {
      id: '/practice/$id'
      path: '/practice/$id'
      fullPath: '/practice/$id'
      preLoaderRoute: typeof PracticeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapter/$id': {
      id: '/chapter/$id'
      path: '/chapter/$id'
      fullPath: '/chapter/$id'
      preLoaderRoute: typeof ChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$chapterId/$lessonId': {
      id: '/lesson/$chapterId/$lessonId'
      path: '/lesson/$chapterId/$lessonId'
      fullPath: '/lesson/$chapterId/$lessonId'
      preLoaderRoute: typeof LessonChapterIdLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  LearnRoute: LearnRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  RankingsRoute: RankingsRoute,
  RankingsbackupRoute: RankingsbackupRoute,
  SupportRoute: SupportRoute,
  TestsRoute: TestsRoute,
  WispyRoute: WispyRoute,
  ChapterIdRoute: ChapterIdRoute,
  PracticeIdRoute: PracticeIdRoute,
  ProfileEditRoute: ProfileEditRoute,
  SubjectIdRoute: SubjectIdRoute,
  LessonChapterIdLessonIdRoute: LessonChapterIdLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
